// Package regen provides deterministic Pkl source regeneration for AutomationConfig.
// Output is deterministic: triggers/conditions/actions in proto list order;
// Starlark blocks annotated with locked-region markers for PklSourcePane tinting.
package regen

import (
	"bytes"
	"fmt"
	"strings"

	configpb "github.com/fdatoo/switchyard/gen/switchyard/config/v1"
)

// Render serializes an AutomationConfig to its canonical .pkl representation.
// The output is deterministic across calls with equal input. The emitted file
// is a valid standalone Pkl module that amends switchyard:automation,
// suitable for one-file-per-automation auto-discovery under
// <configDir>/automations/<id>.pkl.
func Render(ac *configpb.AutomationConfig) ([]byte, error) {
	var buf bytes.Buffer
	w := &pklWriter{b: &buf}
	w.line(`amends "switchyard:automation"`)
	w.line(`import "switchyard:automations" as auto`)
	w.line("")
	w.line("// Auto-generated by switchyardd regen — do not edit manually.")
	w.line("")
	w.line(fmt.Sprintf("id = %q", ac.GetId()))
	w.line(fmt.Sprintf("enabled = %v", ac.GetEnabled()))
	modeStr := automationModeStr(ac.GetMode())
	if modeStr != "single" {
		w.line(fmt.Sprintf("mode = %q", modeStr))
	}
	if ac.GetMaxQueued() > 0 && ac.GetMaxQueued() != 10 {
		w.line(fmt.Sprintf("maxQueued = %d", ac.GetMaxQueued()))
	}

	w.line("triggers {")
	for _, tc := range ac.GetTriggers() {
		renderTrigger(w, tc)
	}
	w.line("}")

	if len(ac.GetConditions()) > 0 {
		w.line("conditions {")
		for _, cc := range ac.GetConditions() {
			renderCondition(w, cc, 1)
		}
		w.line("}")
	}

	w.line("actions {")
	for _, act := range ac.GetActions() {
		renderAction(w, act, 1)
	}
	w.line("}")

	if ac.GetOnFailure() != nil {
		renderOnFailure(w, ac.GetOnFailure())
	}

	return buf.Bytes(), nil
}

func automationModeStr(m configpb.AutomationConfig_Mode) string {
	switch m {
	case configpb.AutomationConfig_MODE_QUEUED:
		return "queued"
	case configpb.AutomationConfig_MODE_RESTART:
		return "restart"
	case configpb.AutomationConfig_MODE_PARALLEL:
		return "parallel"
	default:
		return "single"
	}
}

func renderTrigger(w *pklWriter, tc *configpb.TriggerConfig) {
	switch k := tc.GetKind().(type) {
	case *configpb.TriggerConfig_StateChange:
		sc := k.StateChange
		w.line("  new auto.StateChangeTrigger {")
		if len(sc.GetEntities()) > 0 {
			w.line("    entities {")
			for _, e := range sc.GetEntities() {
				w.line(fmt.Sprintf("      %q", e))
			}
			w.line("    }")
		}
		if sc.GetFrom() != "" {
			w.line(fmt.Sprintf("    from = %q", sc.GetFrom()))
		}
		if sc.GetTo() != "" {
			w.line(fmt.Sprintf("    to = %q", sc.GetTo()))
		}
		if sc.GetForDurNs() > 0 {
			w.line(fmt.Sprintf("    forDur = %d.ns", sc.GetForDurNs()))
		}
		w.line("  }")
	case *configpb.TriggerConfig_Event:
		ev := k.Event
		w.line("  new auto.EventTrigger {")
		w.line(fmt.Sprintf("    kind = %q", ev.GetKind()))
		if len(ev.GetData()) > 0 {
			w.line("    data {")
			for key, val := range ev.GetData() {
				w.line(fmt.Sprintf("      [%q] = %q", key, val))
			}
			w.line("    }")
		}
		w.line("  }")
	case *configpb.TriggerConfig_Time:
		tt := k.Time
		w.line("  new auto.TimeTrigger {")
		if tt.GetAt() != "" {
			w.line(fmt.Sprintf("    at = %q", tt.GetAt()))
		}
		if tt.GetCron() != "" {
			w.line(fmt.Sprintf("    cron = %q", tt.GetCron()))
		}
		if tt.GetEveryNs() > 0 {
			w.line(fmt.Sprintf("    every = %d.ns", tt.GetEveryNs()))
		}
		w.line("  }")
	case *configpb.TriggerConfig_Webhook:
		wh := k.Webhook
		w.line("  new auto.WebhookTrigger {")
		w.line(fmt.Sprintf("    path = %q", wh.GetPath()))
		if len(wh.GetMethods()) > 0 {
			w.line("    methods {")
			for _, m := range wh.GetMethods() {
				w.line(fmt.Sprintf("      %q", m))
			}
			w.line("    }")
		}
		w.line("  }")
	}
}

func renderCondition(w *pklWriter, cc *configpb.ConditionConfig, depth int) {
	indent := strings.Repeat("  ", depth)
	switch k := cc.GetKind().(type) {
	case *configpb.ConditionConfig_State:
		sc := k.State
		w.line(indent + "new auto.StateCondition {")
		w.line(fmt.Sprintf(indent+"  entity = %q", sc.GetEntity()))
		if sc.GetEquals() != "" {
			w.line(fmt.Sprintf(indent+"  equals = %q", sc.GetEquals()))
		}
		if sc.GetNot() != "" {
			w.line(fmt.Sprintf(indent+"  not = %q", sc.GetNot()))
		}
		if len(sc.GetOneOf()) > 0 {
			w.line(indent + "  oneOf {")
			for _, v := range sc.GetOneOf() {
				w.line(fmt.Sprintf(indent+"    %q", v))
			}
			w.line(indent + "  }")
		}
		w.line(indent + "}")
	case *configpb.ConditionConfig_Numeric:
		nc := k.Numeric
		w.line(indent + "new auto.NumericCondition {")
		w.line(fmt.Sprintf(indent+"  entity = %q", nc.GetEntity()))
		if nc.GetAttribute() != "" && nc.GetAttribute() != "value" {
			w.line(fmt.Sprintf(indent+"  attribute = %q", nc.GetAttribute()))
		}
		w.line(fmt.Sprintf(indent+"  op = %q", nc.GetOp()))
		w.line(fmt.Sprintf(indent+"  value = %g", nc.GetValue()))
		w.line(indent + "}")
	case *configpb.ConditionConfig_Time:
		tc := k.Time
		w.line(indent + "new auto.TimeCondition {")
		if tc.GetAfter() != "" {
			w.line(fmt.Sprintf(indent+"  after = %q", tc.GetAfter()))
		}
		if tc.GetBefore() != "" {
			w.line(fmt.Sprintf(indent+"  before = %q", tc.GetBefore()))
		}
		if len(tc.GetWeekdays()) > 0 {
			w.line(indent + "  weekdays {")
			for _, d := range tc.GetWeekdays() {
				w.line(fmt.Sprintf(indent+"    %q", d))
			}
			w.line(indent + "  }")
		}
		w.line(indent + "}")
	case *configpb.ConditionConfig_Starlark:
		// Starlark conditions are locked; wrap with region markers.
		w.line(indent + "// locked-region:starlark")
		w.line(indent + "new auto.StarlarkCondition {")
		w.line(fmt.Sprintf(indent+"  expr = #\"\"\"\n%s\n%s\"\"\"#", k.Starlark.GetExpr(), indent))
		w.line(indent + "}")
		w.line(indent + "// end-locked-region")
	case *configpb.ConditionConfig_And:
		w.line(indent + "new auto.AndCondition {")
		w.line(indent + "  all {")
		for _, child := range k.And.GetAll() {
			renderCondition(w, child, depth+2)
		}
		w.line(indent + "  }")
		w.line(indent + "}")
	case *configpb.ConditionConfig_Or:
		w.line(indent + "new auto.OrCondition {")
		w.line(indent + "  any {")
		for _, child := range k.Or.GetAny() {
			renderCondition(w, child, depth+2)
		}
		w.line(indent + "  }")
		w.line(indent + "}")
	case *configpb.ConditionConfig_Not:
		w.line(indent + "new auto.NotCondition {")
		w.line(indent + "  not =")
		renderCondition(w, k.Not.GetNot(), depth+1)
		w.line(indent + "}")
	}
}

func renderAction(w *pklWriter, act *configpb.ActionConfig, depth int) {
	indent := strings.Repeat("  ", depth)
	switch k := act.GetKind().(type) {
	case *configpb.ActionConfig_CallService:
		cs := k.CallService
		w.line(indent + "new auto.CallServiceAction {")
		w.line(fmt.Sprintf(indent+"  entity = %q", cs.GetEntity()))
		w.line(fmt.Sprintf(indent+"  capability = %q", cs.GetCapability()))
		if len(cs.GetArgs()) > 0 {
			w.line(indent + "  args {")
			for key, val := range cs.GetArgs() {
				w.line(fmt.Sprintf(indent+"    [%q] = %q", key, val))
			}
			w.line(indent + "  }")
		}
		if act.GetContinueOnError() {
			w.line(indent + "  continueOnError = true")
		}
		w.line(indent + "}")
	case *configpb.ActionConfig_Scene:
		w.line(indent + "new auto.SceneAction {")
		w.line(fmt.Sprintf(indent+"  slug = %q", k.Scene.GetSlug()))
		w.line(indent + "}")
	case *configpb.ActionConfig_Script:
		sc := k.Script
		w.line(indent + "new auto.ScriptAction {")
		w.line(fmt.Sprintf(indent+"  name = %q", sc.GetName()))
		if len(sc.GetArgs()) > 0 {
			w.line(indent + "  args {")
			for key, val := range sc.GetArgs() {
				w.line(fmt.Sprintf(indent+"    [%q] = %q", key, val))
			}
			w.line(indent + "  }")
		}
		w.line(indent + "}")
	case *configpb.ActionConfig_Starlark:
		// Starlark actions are locked.
		w.line(indent + "// locked-region:starlark")
		w.line(indent + "new auto.StarlarkAction {")
		w.line(fmt.Sprintf(indent+"  body = #\"\"\"\n%s\n%s\"\"\"#", k.Starlark.GetBody(), indent))
		w.line(indent + "}")
		w.line(indent + "// end-locked-region")
	case *configpb.ActionConfig_Wait:
		w.line(indent + "new auto.WaitAction {")
		w.line(fmt.Sprintf(indent+"  duration = %d.ns", k.Wait.GetDurationNs()))
		w.line(indent + "}")
	case *configpb.ActionConfig_Sequence:
		w.line(indent + "new auto.SequenceBlock {")
		w.line(indent + "  actions {")
		for _, child := range k.Sequence.GetActions() {
			renderAction(w, child, depth+2)
		}
		w.line(indent + "  }")
		w.line(indent + "}")
	case *configpb.ActionConfig_Parallel:
		w.line(indent + "new auto.ParallelBlock {")
		w.line(indent + "  actions {")
		for _, child := range k.Parallel.GetActions() {
			renderAction(w, child, depth+2)
		}
		w.line(indent + "  }")
		w.line(indent + "}")
	}
}

func renderOnFailure(w *pklWriter, ofc *configpb.OnFailureConfig) {
	switch s := ofc.GetStrategy().(type) {
	case *configpb.OnFailureConfig_Ignore:
		// IgnoreStrategy is the default; omit for cleanliness.
		_ = s
	case *configpb.OnFailureConfig_Retry:
		r := s.Retry
		w.line("onFailure = new auto.RetryStrategy {")
		w.line(fmt.Sprintf("  maxAttempts = %d", r.GetMaxAttempts()))
		if r.GetBackoffNs() > 0 {
			w.line(fmt.Sprintf("  backoff = %d.ns", r.GetBackoffNs()))
		}
		w.line("}")
	case *configpb.OnFailureConfig_Notify:
		n := s.Notify
		w.line("onFailure = new auto.NotifyStrategy {")
		w.line(fmt.Sprintf("  entity = %q", n.GetEntity()))
		w.line(fmt.Sprintf("  message = %q", n.GetMessage()))
		w.line("}")
	}
}

type pklWriter struct{ b *bytes.Buffer }

func (w *pklWriter) line(s string) { w.b.WriteString(s + "\n") }
