package regen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/fdatoo/switchyard/internal/dashboard"
)

// Render serializes a DashboardData to its canonical .layout.pkl representation.
// Output is deterministic: widgets sorted by ID, props alphabetical.
func Render(d *dashboard.DashboardData) ([]byte, error) {
	var buf bytes.Buffer
	w := &pklWriter{b: &buf}
	w.line(`import "switchyard:dashboards" as d`)
	w.line(`import "switchyard:widgets" as widgetmod`)
	w.line("")
	w.line("// Auto-generated by switchyardd regen — do not edit manually.")
	w.line("")
	grid := normalizeGrid(d.Grid)
	w.line(fmt.Sprintf("grid: widgetmod.Grid = new { columns = %d; rowHeight = %d }", grid.Columns, grid.RowHeight))
	w.line("widgets: Listing<widgetmod.WidgetInstance> = new {")
	widgets := sortedWidgets(d.Widgets)
	for _, wi := range widgets {
		renderWidget(w, wi, 1)
	}
	w.line("}")
	return buf.Bytes(), nil
}

func renderWidget(w *pklWriter, wi dashboard.WidgetData, depth int) {
	indent := strings.Repeat("  ", depth)
	className := "d.LeafWidget"
	if wi.IsContainer {
		className = "d.ContainerWidget"
	}
	w.raw(indent + "new " + className + " {\n")
	w.raw(fmt.Sprintf("%s  id = %q\n", indent, wi.ID))
	if !wi.IsContainer {
		w.raw(fmt.Sprintf("%s  widgetClass = %q\n", indent, wi.ClassID))
	}
	w.raw(fmt.Sprintf("%s  pos = new widgetmod.Position { x = %d; y = %d; width = %d; height = %d }\n",
		indent, wi.Pos.X, wi.Pos.Y, wi.Pos.W, wi.Pos.H))
	if len(wi.Props) > 0 {
		keys := make([]string, 0, len(wi.Props))
		for k := range wi.Props {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		w.raw(indent + "  props {\n")
		for _, k := range keys {
			w.raw(fmt.Sprintf("%s    [%q] = %s\n", indent, k, formatPklValue(wi.Props[k])))
		}
		w.raw(indent + "  }\n")
	}
	if wi.IsContainer {
		childGrid := normalizeGrid(wi.ChildGrid)
		w.raw(fmt.Sprintf("%s  childGrid = new widgetmod.Grid { columns = %d; rowHeight = %d }\n",
			indent, childGrid.Columns, childGrid.RowHeight))
	}
	if wi.IsContainer && len(wi.Children) > 0 {
		w.raw(indent + "  children {\n")
		for _, child := range sortedWidgets(wi.Children) {
			renderWidget(w, child, depth+2)
		}
		w.raw(indent + "  }\n")
	}
	w.raw(indent + "}\n")
}

func normalizeGrid(g dashboard.GridData) dashboard.GridData {
	if g.Columns == 0 {
		g.Columns = 12
	}
	if g.RowHeight == 0 {
		g.RowHeight = 60
	}
	return g
}

func formatPklValue(v any) string {
	switch tv := v.(type) {
	case string:
		return fmt.Sprintf("%q", tv)
	case bool:
		if tv {
			return "true"
		}
		return "false"
	case float64:
		if tv == float64(int64(tv)) {
			return fmt.Sprintf("%d", int64(tv))
		}
		return fmt.Sprintf("%g", tv)
	case int, int32, int64:
		return fmt.Sprintf("%d", tv)
	case nil:
		return "null"
	default:
		return fmt.Sprintf("%q", fmt.Sprintf("%v", tv))
	}
}

func sortedWidgets(ws []dashboard.WidgetData) []dashboard.WidgetData {
	sorted := make([]dashboard.WidgetData, len(ws))
	copy(sorted, ws)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })
	return sorted
}

type pklWriter struct{ b *bytes.Buffer }

func (w *pklWriter) line(s string) { w.b.WriteString(s + "\n") }
func (w *pklWriter) raw(s string)  { w.b.WriteString(s) }
