import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import { PklSourcePane } from "./PklSourcePane";

const SAMPLE_SOURCE = `import "switchyard:automations" as auto

// Auto-generated by switchyardd regen
new auto.Automation {
  id = "test"
  // locked-region:starlark
  new auto.StarlarkCondition {
    expr = "state.value < 50"
  }
  // end-locked-region
  enabled = true
}`;

describe("PklSourcePane", () => {
  it("renders all source lines", () => {
    render(<PklSourcePane source={SAMPLE_SOURCE} isDirty={false} />);
    expect(screen.getByText(/import "switchyard:automations"/)).toBeDefined();
    expect(screen.getByText(/enabled = true/)).toBeDefined();
  });

  it("applies locked class to lines inside locked-region markers", () => {
    const { container } = render(<PklSourcePane source={SAMPLE_SOURCE} isDirty={false} />);
    const lockedRows = container.querySelectorAll(".pkl-source-pane__line--locked");
    // Lines from "// locked-region:starlark" onward (inclusive until // end-locked-region)
    expect(lockedRows.length).toBeGreaterThan(0);
  });

  it("applies dirty class to non-locked lines when isDirty=true", () => {
    const { container } = render(<PklSourcePane source={SAMPLE_SOURCE} isDirty={true} />);
    const dirtyRows = container.querySelectorAll(".pkl-source-pane__line--dirty");
    expect(dirtyRows.length).toBeGreaterThan(0);
  });

  it("shows diff tab button with count when isDirty=true", () => {
    render(<PklSourcePane source={SAMPLE_SOURCE} isDirty={true} />);
    const diffTab = screen.getByRole("tab", { name: /diff vs disk/i });
    expect(diffTab.textContent).toContain("(");
    // The count should be > 0
    const match = diffTab.textContent?.match(/\((\d+)\)/);
    expect(match).toBeTruthy();
    expect(Number(match?.[1])).toBeGreaterThan(0);
  });
});
